name: Matrix

on: [push]

jobs:
  linux:
    name: Linux ${{ matrix.os }} (${{ matrix.build-type }}, ${{ matrix.compiler }}, ${{ matrix.cxx11-standard }}, ${{ matrix.library-type }})
    runs-on: ubuntu-latest
    container:
      image: dynawo/dynawo-ci-nightly-${{ matrix.os }}:latest
      options: --user root
    strategy:
      matrix:
        os: [fedora, bionic]
        build-type: [Release, Debug]
        cxx11-standard: [YES, NO]
        compiler: [GCC, CLANG]
        library-type: [SHARED, STATIC]
    env:
      BUILD_TYPE: ${{ matrix.build-type }}
      CXX11_ENABLED: ${{ matrix.cxx11-standard }}
      COMPILER: ${{ matrix.compiler }}
      DYNAWO_LIBRARY_TYPE: ${{ matrix.library-type }}

    steps:
      - name: Echo
        run: echo $BUILD_TYPE $CXX11_ENABLED $COMPILER $DYNAWO_LIBRARY_TYPE

      - name: Echo tests
        if: ${{ matrix.build-type == 'Debug' && matrix.library-type == 'SHARED' }}
        run: echo Tests

  macos:
    name: MacOS
    runs-on: macos-latest

    strategy:
      matrix:
        build-type: [Release, Debug]
        library-type: [SHARED, STATIC]
    steps:
      - name: Echo
        run: echo $BUILD_TYPE $CXX11_ENABLED $COMPILER $DYNAWO_LIBRARY_TYPE
