name: Nightly

on:
  schedule:
    - cron:  '0 0 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Log
        run: |
          git branch
          git log
